#!/bin/bash
# Post-mode hook for ORCHESTRATION mode
# Runs after a multi-agent orchestration session completes

set -e

MODE="ORCHESTRATION"
SESSION_ID="${1:-$(date +%s)}"
DELEGADO_HOME="${DELEGADO_HOME:-/root/projects/delegate-os}"
OBSIDIAN_VAULT="${OBSIDIAN_VAULT:-/root/obsidian-vault}"

log() {
    echo "[post_${MODE}] $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

SESSION_DIR="$DELEGADO_HOME/.delegado/sessions/$SESSION_ID"
mkdir -p "$SESSION_DIR"

# Archive orchestration session state
if [ -f "$DELEGADO_HOME/.delegado/current_session.md" ]; then
    cp "$DELEGADO_HOME/.delegado/current_session.md" \
       "$SESSION_DIR/orchestration_output.md"
fi

# Archive context if exists
if [ -f "$DELEGADO_HOME/.delegado/context.md" ]; then
    cp "$DELEGADO_HOME/.delegado/context.md" \
       "$SESSION_DIR/context.md"
fi

# Archive task results
mkdir -p "$SESSION_DIR/tasks"
for task_result in "$DELEGADO_HOME"/.delegado/tasks/*.md; do
    [ -f "$task_result" ] && cp "$task_result" "$SESSION_DIR/tasks/"
done 2>/dev/null

# Sync orchestration summary to Obsidian
if [ -d "$OBSIDIAN_VAULT" ]; then
    OBSIDIAN_DIR="$OBSIDIAN_VAULT/00-ORCHESTRATION"
    mkdir -p "$OBSIDIAN_DIR"
    
    cat > "$OBSIDIAN_DIR/session-$SESSION_ID.md" << 'OBSIDIAN_EOF'
---
type: orchestration-session
session_id: %SESSION_ID%
completed: %TIMESTAMP%
tags: [delegado, orchestration, multi-agent, done]
---

# Multi-Agent Orchestration Session Complete

## Session Overview

## Modes Invoked

## Tasks Completed

## Results Integrated

## Context Maintained

## Next Actions

---
*Generated by Delegado OS - ORCHESTRATION Mode*
OBSIDIAN_EOF

    sed -i "s/%SESSION_ID%/$SESSION_ID/g; s/%TIMESTAMP%/$(date -Iseconds)/g" \
        "$OBSIDIAN_DIR/session-$SESSION_ID.md"
    log "Synced to Obsidian"
fi

# Update orchestration metrics
echo "{\"mode\":\"$MODE\",\"session\":\"$SESSION_ID\",\"completed\":\"$(date -Iseconds)\"}" >> \
    "$DELEGADO_HOME/.delegado/sessions.jsonl" 2>/dev/null || true

# Cleanup session state
rm -f "$DELEGADO_HOME/.delegado/current_session.md"
rm -f "$DELEGADO_HOME/.delegado/context.md"

log "Post-hook complete for orchestration session $SESSION_ID"
