#!/bin/bash
# Post-mode hook for PROFESSOR mode
# Runs after a PROFESSOR teaching session completes

set -e

MODE="PROFESSOR"
SESSION_ID="${1:-$(date +%s)}"
DELEGADO_HOME="${DELEGADO_HOME:-/root/projects/delegate-os}"
OBSIDIAN_VAULT="${OBSIDIAN_VAULT:-/root/obsidian-vault}"

log() {
    echo "[post_${MODE}] $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

# Create session archive directory
SESSION_DIR="$DELEGADO_HOME/.delegado/sessions/$SESSION_ID"
mkdir -p "$SESSION_DIR"

# Find and archive the teaching output
if [ -f "$DELEGADO_HOME/.delegado/current_session.md" ]; then
    cp "$DELEGADO_HOME/.delegado/current_session.md" \
       "$SESSION_DIR/professor_output.md"
    log "Archived teaching output"
fi

# Sync to Obsidian if vault is configured
if [ -d "$OBSIDIAN_VAULT" ]; then
    OBSIDIAN_DIR="$OBSIDIAN_VAULT/00-PROFESSOR"
    mkdir -p "$OBSIDIAN_DIR"
    
    # Create session note
    cat > "$OBSIDIAN_DIR/session-$SESSION_ID.md" << 'OBSIDIAN_EOF'
---
type: professor-session
session_id: %SESSION_ID%
completed: %TIMESTAMP%
tags: [delegado, teaching, done]
---

# Professor Session Complete

## Session Summary

<!-- Content auto-filled from session -->

## Topics Covered

- 

## Next Steps

- Review the material
- Practice exercises
- Apply concepts in real project

---
*Generated by Delegado OS - PROFESSOR Mode*
OBSIDIAN_EOF

    sed -i "s/%SESSION_ID%/$SESSION_ID/g" "$OBSIDIAN_DIR/session-$SESSION_ID.md"
    sed -i "s/%TIMESTAMP%/$(date -Iseconds)/g" "$OBSIDIAN_DIR/session-$SESSION_ID.md"
    
    log "Synced to Obsidian: $OBSIDIAN_DIR/session-$SESSION_ID.md"
fi

# Update metrics
METRICS_FILE="$DELEGADO_HOME/.delegado/metrics.json"
mkdir -p "$DELEGADO_HOME/.delegado"

if [ -f "$METRICS_FILE" ]; then
    # Add session to metrics (simple append)
    echo "{\"mode\":\"$MODE\",\"session\":\"$SESSION_ID\",\"completed\":\"$(date -Iseconds)\"}" >> \
        "$DELEGADO_HOME/.delegado/sessions.jsonl" 2>/dev/null || true
else
    echo "{\"mode\":\"$MODE\",\"session\":\"$SESSION_ID\",\"completed\":\"$(date -Iseconds)\"}" > \
        "$DELEGADO_HOME/.delegado/sessions.jsonl"
fi

# Cleanup current session
rm -f "$DELEGADO_HOME/.delegado/current_session.md"

log "Post-hook complete for session $SESSION_ID"
