#!/bin/bash
# Post-mode hook for RESEARCHER mode
# Runs after a research session completes

set -e

MODE="RESEARCHER"
SESSION_ID="${1:-$(date +%s)}"
DELEGADO_HOME="${DELEGADO_HOME:-/root/projects/delegate-os}"
OBSIDIAN_VAULT="${OBSIDIAN_VAULT:-/root/obsidian-vault}"

log() {
    echo "[post_${MODE}] $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

SESSION_DIR="$DELEGADO_HOME/.delegado/sessions/$SESSION_ID"
mkdir -p "$SESSION_DIR"

[ -f "$DELEGADO_HOME/.delegado/current_session.md" ] && \
    cp "$DELEGADO_HOME/.delegado/current_session.md" "$SESSION_DIR/researcher_output.md"

# Sync research to Obsidian
if [ -d "$OBSIDIAN_VAULT" ]; then
    OBSIDIAN_DIR="$OBSIDIAN_VAULT/00-RESEARCHER"
    mkdir -p "$OBSIDIAN_DIR"
    
    cat > "$OBSIDIAN_DIR/session-$SESSION_ID.md" << 'OBSIDIAN_EOF'
---
type: researcher-session
session_id: %SESSION_ID%
completed: %TIMESTAMP%
tags: [delegado, research, done]
---

# Research Session Complete

## Research Question

## Sources Analyzed

## Key Findings

## Conclusions

## References

---
*Generated by Delegado OS - RESEARCHER Mode*
OBSIDIAN_EOF

    sed -i "s/%SESSION_ID%/$SESSION_ID/g; s/%TIMESTAMP%/$(date -Iseconds)/g" \
        "$OBSIDIAN_DIR/session-$SESSION_ID.md"
    log "Synced to Obsidian"
fi

echo "{\"mode\":\"$MODE\",\"session\":\"$SESSION_ID\",\"completed\":\"$(date -Iseconds)\"}" >> \
    "$DELEGADO_HOME/.delegado/sessions.jsonl" 2>/dev/null || true

rm -f "$DELEGADO_HOME/.delegado/current_session.md"
log "Post-hook complete"
