#!/bin/bash
# Post-mode hook for DEBUGGER mode
# Runs after a debugging session completes

set -e

MODE="DEBUGGER"
SESSION_ID="${1:-$(date +%s)}"
DELEGADO_HOME="${DELEGADO_HOME:-/root/projects/delegate-os}"
OBSIDIAN_VAULT="${OBSIDIAN_VAULT:-/root/obsidian-vault}"

log() {
    echo "[post_${MODE}] $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

SESSION_DIR="$DELEGADO_HOME/.delegado/sessions/$SESSION_ID"
mkdir -p "$SESSION_DIR"

# Archive debug output
if [ -f "$DELEGADO_HOME/.delegado/current_session.md" ]; then
    cp "$DELEGADO_HOME/.delegado/current_session.md" \
       "$SESSION_DIR/debugger_output.md"
fi

# Sync to Obsidian - Knowledge base for future debugging
if [ -d "$OBSIDIAN_VAULT" ]; then
    OBSIDIAN_DIR="$OBSIDIAN_VAULT/00-DEBUGGER"
    mkdir -p "$OBSIDIAN_DIR"
    
    cat > "$OBSIDIAN_DIR/session-$SESSION_ID.md" << 'OBSIDIAN_EOF'
---
type: debugger-session
session_id: %SESSION_ID%
completed: %TIMESTAMP%
tags: [delegado, debugging, resolved]
---

# Debugging Session Complete

## Problem Summary

## Root Cause

## Solution Applied

## Lessons Learned

## Related Issues

---
*Generated by Delegado OS - DEBUGGER Mode*
OBSIDIAN_EOF

    sed -i "s/%SESSION_ID%/$SESSION_ID/g" "$OBSIDIAN_DIR/session-$SESSION_ID.md"
    sed -i "s/%TIMESTAMP%/$(date -Iseconds)/g" "$OBSIDIAN_DIR/session-$SESSION_ID.md"
    log "Synced to Obsidian knowledge base"
fi

echo "{\"mode\":\"$MODE\",\"session\":\"$SESSION_ID\",\"completed\":\"$(date -Iseconds)\"}" >> \
    "$DELEGADO_HOME/.delegado/sessions.jsonl" 2>/dev/null || true

rm -f "$DELEGADO_HOME/.delegado/current_session.md"
log "Post-hook complete"
