#!/bin/bash
# Post-mode hook for MENTOR mode
# Runs after a career mentoring session completes

set -e

MODE="MENTOR"
SESSION_ID="${1:-$(date +%s)}"
DELEGADO_HOME="${DELEGADO_HOME:-/root/projects/delegate-os}"
OBSIDIAN_VAULT="${OBSIDIAN_VAULT:-/root/obsidian-vault}"

log() {
    echo "[post_${MODE}] $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

SESSION_DIR="$DELEGADO_HOME/.delegado/sessions/$SESSION_ID"
mkdir -p "$SESSION_DIR"

[ -f "$DELEGADO_HOME/.delegado/current_session.md" ] && \
    cp "$DELEGADO_HOME/.delegado/current_session.md" "$SESSION_DIR/mentor_output.md"

# Sync career development notes to Obsidian
if [ -d "$OBSIDIAN_VAULT" ]; then
    OBSIDIAN_DIR="$OBSIDIAN_VAULT/00-MENTOR"
    mkdir -p "$OBSIDIAN_DIR"
    
    cat > "$OBSIDIAN_DIR/session-$SESSION_ID.md" << 'OBSIDIAN_EOF'
---
type: mentor-session
session_id: %SESSION_ID%
completed: %TIMESTAMP%
tags: [delegado, career, mentoring]
---

# Career Mentoring Session Complete

## Goals Discussed

## Action Items

## Resources Recommended

## Next Milestone

---
*Generated by Delegado OS - MENTOR Mode*
OBSIDIAN_EOF

    sed -i "s/%SESSION_ID%/$SESSION_ID/g; s/%TIMESTAMP%/$(date -Iseconds)/g" \
        "$OBSIDIAN_DIR/session-$SESSION_ID.md"
    log "Synced to Obsidian"
fi

echo "{\"mode\":\"$MODE\",\"session\":\"$SESSION_ID\",\"completed\":\"$(date -Iseconds)\"}" >> \
    "$DELEGADO_HOME/.delegado/sessions.jsonl" 2>/dev/null || true

rm -f "$DELEGADO_HOME/.delegado/current_session.md"
log "Post-hook complete"
