#!/bin/bash
# Post-mode hook for GUARDIAN mode
# Runs after a security/guardian session completes

set -e

MODE="GUARDIAN"
SESSION_ID="${1:-$(date +%s)}"
DELEGADO_HOME="${DELEGADO_HOME:-/root/projects/delegate-os}"
OBSIDIAN_VAULT="${OBSIDIAN_VAULT:-/root/obsidian-vault}"

log() {
    echo "[post_${MODE}] $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

SESSION_DIR="$DELEGADO_HOME/.delegado/sessions/$SESSION_ID"
mkdir -p "$SESSION_DIR"

# Archive security output
[ -f "$DELEGADO_HOME/.delegado/current_session.md" ] && \
    cp "$DELEGADO_HOME/.delegado/current_session.md" "$SESSION_DIR/guardian_output.md"

# Sync to Obsidian - Security knowledge base
if [ -d "$OBSIDIAN_VAULT" ]; then
    OBSIDIAN_DIR="$OBSIDIAN_VAULT/00-GUARDIAN"
    mkdir -p "$OBSIDIAN_DIR"
    
    cat > "$OBSIDIAN_DIR/session-$SESSION_ID.md" << 'OBSIDIAN_EOF'
---
type: guardian-session
session_id: %SESSION_ID%
completed: %TIMESTAMP%
tags: [delegado, security, guardian]
---

# Guardian Security Session Complete

## Security Issues Found

## OWASP Categories

## Mitigations Applied

## Recommendations

---
*Generated by Delegado OS - GUARDIAN Mode*
OBSIDIAN_EOF

    sed -i "s/%SESSION_ID%/$SESSION_ID/g; s/%TIMESTAMP%/$(date -Iseconds)/g" \
        "$OBSIDIAN_DIR/session-$SESSION_ID.md"
    log "Synced to Obsidian"
fi

echo "{\"mode\":\"$MODE\",\"session\":\"$SESSION_ID\",\"completed\":\"$(date -Iseconds)\"}" >> \
    "$DELEGADO_HOME/.delegado/sessions.jsonl" 2>/dev/null || true

rm -f "$DELEGADO_HOME/.delegado/current_session.md"
log "Post-hook complete"
