#!/bin/bash
#===============================================================================
# Delegado OS - Documentation Generator
# Generates README, index, and cross-references
#===============================================================================

set -e

DELEGADO_ROOT="${DELEGADO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
OUTPUT_DIR="$DELEGADO_ROOT/docs"

mkdir -p "$OUTPUT_DIR"

#-------------------------------------------------------------------------------
# Generate Index
#-------------------------------------------------------------------------------
generate_index() {
    local index_file="$DELEGADO_ROOT/INDEX.md"
    
    cat > "$index_file" << 'HEADER'
# Delegado OS - Documentation Index

> Meta-prompting agent system with multi-mode orchestration

## 📚 Documentation

### Core Documentation
| Document | Description |
|----------|-------------|
| [README.md](README.md) | Main project documentation |
| [META-PROMPTING.md](META-PROMPTING.md) | Core meta-prompting framework |
| [HELL-OBSIDIAN.md](docs/HELL-OBSIDIAN.md) | HELL + Obsidian integration |

### Agent Modes
| Mode | Description | Guide | Template |
|------|-------------|-------|----------|
| [PROFESSOR](subagents/PROFESSOR/) | Teaching & docs | [TEACHING-METHODOLOGIES.md](subagents/PROFESSOR/TEACHING/TEACHING-METHODOLOGIES.md) | [TEMPLATE](templates/obsidian/TEMPLATE-PROFESSOR.md) |
| [ARCHITECT](subagents/ARCHITECT/) | System design | [ARCHITECTURAL-PATTERNS.md](subagents/ARCHITECT/PATTERNS/ARCHITECTURAL-PATTERNS.md) | [TEMPLATE](templates/obsidian/TEMPLATE-ARCHITECT.md) |
| [DEBUGGER](subagents/DEBUGGER/) | Bug analysis | [DEBUGGING-TECHNIQUES.md](subagents/DEBUGGER/ANALYSIS/DEBUGGING-TECHNIQUES.md) | [TEMPLATE](templates/obsidian/TEMPLATE-DEBUGGER.md) |
| [GUARDIAN](subagents/GUARDIAN/) | Security | [SECURITY-PATTERNS.md](subagents/GUARDIAN/SECURITY/SECURITY-PATTERNS.md) | [TEMPLATE](templates/obsidian/TEMPLATE-GUARDIAN.md) |
| [RESEARCHER](subagents/RESEARCHER/) | Tech research | [RESEARCH-METHODS.md](subagents/RESEARCHER/WIDGETS/RESEARCH-METHODS.md) | [TEMPLATE](templates/obsidian/TEMPLATE-RESEARCHER.md) |
| [MENTOR](subagents/MENTOR/) | Career growth | [CAREER-DEVELOPMENT.md](subagents/MENTOR/CAREER/CAREER-DEVELOPMENT.md) | [TEMPLATE](templates/obsidian/TEMPLATE-MENTOR.md) |
| [CONSULTANT](subagents/CONSULTANT/) | Strategy | [CONSULTING-FRAMES.md](subagents/CONSULTANT/STRATEGY/CONSULTING-FRAMES.md) | [TEMPLATE](templates/obsidian/TEMPLATE-CONSULTANT.md) |

### Scripts & Automation
| Script | Purpose |
|--------|---------|
| [delegate.sh](scripts/delegate.sh) | Main orchestrator |
| [context7_search.sh](scripts/context7_search.sh) | Documentation search |
| [mode_selector.sh](scripts/mode_selector.sh) | Interactive mode selection |
| [hooks.sh](scripts/hooks.sh) | Execution hooks |
| [auto_improve.sh](scripts/auto_improve.sh) | Self-analysis |

### Hooks
| Hook | Trigger |
|------|---------|
| [pre_PROFESSOR.sh](scripts/hooks.d/pre_PROFESSOR.sh) | Before professor mode |
| [pre_ARCHITECT.sh](scripts/hooks.d/pre_ARCHITECT.sh) | Before architect mode |
| [pre_DEBUGGER.sh](scripts/hooks.d/pre_DEBUGGER.sh) | Before debugger mode |
| [pre_GUARDIAN.sh](scripts/hooks.d/pre_GUARDIAN.sh) | Before guardian mode |
| [pre_RESEARCHER.sh](scripts/hooks.d/pre_RESEARCHER.sh) | Before researcher mode |
| [pre_MENTOR.sh](scripts/hooks.d/pre_MENTOR.sh) | Before mentor mode |
| [pre_CONSULTANT.sh](scripts/hooks.d/pre_CONSULTANT.sh) | Before consultant mode |

### Templates
- [Obsidian Templates](templates/obsidian/) - All mode templates

### Examples
- [PROFESSOR Examples](examples/PROFESSOR/) - Sample teaching sessions
- [ARCHITECT Examples](examples/ARCHITECT/) - Sample architecture docs
- [DEBUGGER Examples](examples/DEBUGGER/) - Sample bug analysis
- [GUARDIAN Examples](examples/GUARDIAN/) - Sample security audits
- [RESEARCHER Examples](examples/RESEARCHER/) - Sample research
- [MENTOR Examples](examples/MENTOR/) - Sample career coaching
- [CONSULTANT Examples](examples/CONSULTANT/) - Sample advisories

---

*Auto-generated by generate_docs.sh*
HEADER
    
    echo "Generated: $index_file"
}

#-------------------------------------------------------------------------------
# Generate README Summary
#-------------------------------------------------------------------------------
generate_readme_summary() {
    local readme_file="$DELEGADO_ROOT/README.md"
    
    # Check if README exists and add mode summary if not present
    if ! grep -q "## 🎭 Agent Modes" "$readme_file" 2>/dev/null; then
        cat >> "$readme_file" << 'MODES_SECTION'

---

## 🎭 Agent Modes

Delegado OS includes 7 specialized agent modes:

| Mode | Trigger | Purpose |
|------|---------|---------|
| **PROFESSOR** 👨‍🏫 | `ensinar`, `aprender` | Teaching & documentation |
| **ARCHITECT** 🏛️ | `pattern`, `design` | System architecture |
| **DEBUGGER** 🐛 | `bug`, `erro` | Bug analysis |
| **GUARDIAN** 🛡️ | `segurança`, `auth` | Security audits |
| **RESEARCHER** 📡 | `comparar`, `biblioteca` | Technology research |
| **MENTOR** 🌱 | `carreira`, `crescer` | Career development |
| **CONSULTANT** 💼 | `sugerir`, `decisão` | Strategic advice |

See [AGENT-MODES.md](AGENT-MODES.md) for full documentation.
MODES_SECTION
        echo "Updated: $readme_file"
    fi
}

#-------------------------------------------------------------------------------
# Generate Quick Start Guide
#-------------------------------------------------------------------------------
generate_quickstart() {
    local qs_file="$OUTPUT_DIR/QUICKSTART.md"
    
    cat > "$qs_file" << 'EOF'
# Delegado OS - Quick Start

## 1. Activate a Mode

```bash
./scripts/delegate.sh activate PROFESSOR
```

## 2. Use the Mode

The agent will automatically:
- Load the mode's SKILL.md
- Set up Obsidian vault folder
- Run pre-mode hooks
- Ready to assist with mode-specific tasks

## 3. Commands

```bash
# List all modes
./scripts/delegate.sh modes

# Activate a mode
./scripts/delegate.sh activate ARCHITECT

# Search docs with Context7
./scripts/delegate.sh search "python testing patterns"

# Sync content to Obsidian
./scripts/delegate.sh sync ./notes.md "My Notes"

# Run self-analysis
./scripts/auto_improve.sh all
```

## 4. Mode Selection

**Automatic:** Just describe what you need and the mode selector will detect:

```
"me ensina TDD" → PROFESSOR mode
"como estruturar esse projeto?" → ARCHITECT mode
"esse bug tá difícil" → DEBUGGER mode
"revisar segurança do login" → GUARDIAN mode
```

**Manual:** Use `/delegado` prefix:
```
/delegado professor "React hooks"
/delegado architect "microservices pattern"
/delegado debugger analyze
```

## 5. Environment Variables

```bash
export DELEGADO_ROOT=/path/to/delegate-os
export OBSIDIAN_VAULT=~/obsidian-vault
export CONTEXT7_API_KEY=your_api_key
```

---

*Auto-generated*
EOF
    
    echo "Generated: $qs_file"
}

#-------------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------------
generate_index
generate_readme_summary
generate_quickstart

echo ""
echo "Documentation generation complete!"
