#!/bin/bash
# Delegado OS - Obsidian Vault Setup Script
# Creates the complete folder structure for all agent modes

set -e

OBSIDIAN_VAULT="${1:-${OBSIDIAN_VAULT:-~/obsidian-vault}}"
DELEGADO_HOME="${DELEGADO_HOME:-/root/projects/delegate-os}"

echo "╔════════════════════════════════════════════════════════════╗"
echo "║      Delegado OS - Obsidian Vault Setup                   ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Vault path: $OBSIDIAN_VAULT"
echo ""

# Create vault directory
mkdir -p "$OBSIDIAN_VAULT"

# Function to create mode folder structure
create_mode_structure() {
    local mode=$1
    local folders=("${@:2}")
    
    echo "  Creating $mode..."
    for folder in "${folders[@]}"; do
        mkdir -p "$OBSIDIAN_VAULT/00-$mode/$folder"
    done
}

# Create HELL framework structure
echo "[1/3] Creating HELL framework structure..."
mkdir -p "$OBSIDIAN_VAULT/00-HELL"/{contexts,milestones,loops,logs}

# Create mode-specific structures
echo "[2/3] Creating mode folders..."

create_mode_structure "PROFESSOR" "lessons" "examples" "exercises" "references"
create_mode_structure "ARCHITECT" "proposals" "patterns" "diagrams" "decisions"
create_mode_structure "DEBUGGER" "bugs" "fixes" "patterns" "memory-leaks"
create_mode_structure "GUARDIAN" "audits" "vulnerabilities" "compliance" "checklists"
create_mode_structure "RESEARCHER" "tech-reviews" "benchmarks" "comparisons" "papers"
create_mode_structure "MENTOR" "sessions" "learning" "goals" "career"
create_mode_structure "CONSULTANT" "proposals" "feasibility" "rfp" "contracts"
create_mode_structure "ORCHESTRATION" "sessions" "results" "contexts"

# Create shared folders
echo "[3/3] Creating shared folders..."
mkdir -p "$OBSIDIAN_VAULT/99-Shared"/{snippets,templates,tags,searches}
mkdir -p "$OBSIDIAN_VAULT/99-Archive"

# Create index files for each mode
create_index() {
    local mode=$1
    local desc=$2
    cat > "$OBSIDIAN_VAULT/00-$mode/README.md" << EOF
# $mode Mode

$desc

## Folder Structure

$(ls -la "$OBSIDIAN_VAULT/00-$mode" 2>/dev/null | tail -n +4 | awk '{print "- " $NF}')

## Recent Sessions

<!-- Auto-populated from sessions -->

## Notes

<!-- Your notes here -->

---
*Managed by Delegado OS*
EOF
}

echo "Creating index files..."
create_index "PROFESSOR" "Teaching and learning sessions for development topics."
create_index "ARCHITECT" "Architecture proposals, patterns, and system design."
create_index "DEBUGGER" "Bug analysis, fixes, and debugging patterns."
create_index "GUARDIAN" "Security audits, vulnerabilities, and compliance."
create_index "RESEARCHER" "Technology research, benchmarks, and comparisons."
create_index "MENTOR" "Career development and mentorship sessions."
create_index "CONSULTANT" "Consulting proposals and feasibility studies."
create_index "ORCHESTRATION" "Multi-agent orchestration sessions and results."

# Create session template
cat > "$OBSIDIAN_VAULT/99-Shared/templates/session-template.md" << 'EOF'
---
type: session
mode: %MODE%
date: %DATE%
tags: []
---

# %MODE% Session - %DATE%

## Objective

<!-- What was the goal of this session? -->

## Key Points

- 

## Decisions Made

- 

## Action Items

- [ ] 

## Notes

<!-- Additional notes -->

## Related Sessions

<!-- Links to related sessions -->

---
*Generated by Delegado OS*
EOF

# Create config file
cat > "$OBSIDIAN_VAULT/.delegado-config" << EOF
# Delegado OS Vault Configuration
# Managed automatically - manual edits may be overwritten

VAULT_VERSION=1.0.0
CREATED=$(date -Iseconds)
DELEGADO_HOME=$DELEGADO_HOME

MODES=(
    PROFESSOR
    ARCHITECT
    DEBUGGER
    GUARDIAN
    RESEARCHER
    MENTOR
    CONSULTANT
    ORCHESTRATION
)

AUTO_SYNC=true
BACKUP_ENABLED=true
EOF

# Set permissions
chmod -R 755 "$OBSIDIAN_VAULT"
chmod 644 "$OBSIDIAN_VAULT"/*/*.md "$OBSIDIAN_VAULT"/.delegado-config 2>/dev/null || true

# Summary
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  ✅ Obsidian Vault Setup Complete!                        ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Vault location: $OBSIDIAN_VAULT"
echo ""
echo "Structure created:"
echo "  ├── 00-HELL/           (HELL framework)"
echo "  ├── 00-PROFESSOR/      (Teaching)"
echo "  ├── 00-ARCHITECT/      (Architecture)"
echo "  ├── 00-DEBUGGER/      (Debugging)"
echo "  ├── 00-GUARDIAN/      (Security)"
echo "  ├── 00-RESEARCHER/    (Research)"
echo "  ├── 00-MENTOR/        (Career)"
echo "  ├── 00-CONSULTANT/    (Consulting)"
echo "  ├── 00-ORCHESTRATION/ (Multi-agent)"
echo "  └── 99-Shared/        (Templates & snippets)"
echo ""
echo "Next steps:"
echo "  1. Open the vault in Obsidian"
echo "  2. Enable Templater plugin"
echo "  3. Configure Delegado OS to use this vault:"
echo "     export OBSIDIAN_VAULT=$OBSIDIAN_VAULT"
echo ""
